name: Build LEDE with extra packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout lede source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext libncurses-dev libssl-dev \
          python3-distutils rsync unzip zlib1g-dev file wget python3-pyelftools ccache

    - name: Clone additional package sources
      run: |
        git clone https://github.com/kenzok8/openwrt-packages package/openwrt-packages
        git clone https://github.com/kenzok8/small package/small

    - name: Remove duplicated packages (keep lean)
      run: |
        dups=$(find package/lean package/openwrt-packages package/small -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort | uniq -d)
        for name in $dups; do
          for path in package/openwrt-packages package/small; do
            [ -d "$path/$name" ] && echo "Removing $path/$name" && rm -rf "$path/$name"
          done
        done

    - name: Update and install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load .config
      run: |
        if [ -f my_config ]; then
          cp my_config .config
        else
          make defconfig
        fi

    - name: Download sources
      run: make download -j8

    - name: Compile firmware
      run: make -j$(nproc)

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: LEDE-firmware
        path: bin/targets

